//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.269
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceForWmsVsFMSDailyCheck.ServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CODParameter", Namespace="http://schemas.datacontract.org/2004/07/Vancl.Finance.Model.Cash")]
    [System.SerializableAttribute()]
    public partial class CODParameter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DateCheckedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExpressIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HouseWhereField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToHouseCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DateChecked {
            get {
                return this.DateCheckedField;
            }
            set {
                if ((this.DateCheckedField.Equals(value) != true)) {
                    this.DateCheckedField = value;
                    this.RaisePropertyChanged("DateChecked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtFrom {
            get {
                return this.DtFromField;
            }
            set {
                if ((this.DtFromField.Equals(value) != true)) {
                    this.DtFromField = value;
                    this.RaisePropertyChanged("DtFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DtTo {
            get {
                return this.DtToField;
            }
            set {
                if ((this.DtToField.Equals(value) != true)) {
                    this.DtToField = value;
                    this.RaisePropertyChanged("DtTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExpressId {
            get {
                return this.ExpressIdField;
            }
            set {
                if ((this.ExpressIdField.Equals(value) != true)) {
                    this.ExpressIdField = value;
                    this.RaisePropertyChanged("ExpressId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormCode {
            get {
                return this.FormCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FormCodeField, value) != true)) {
                    this.FormCodeField = value;
                    this.RaisePropertyChanged("FormCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseCode {
            get {
                return this.HouseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseCodeField, value) != true)) {
                    this.HouseCodeField = value;
                    this.RaisePropertyChanged("HouseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HouseWhere {
            get {
                return this.HouseWhereField;
            }
            set {
                if ((object.ReferenceEquals(this.HouseWhereField, value) != true)) {
                    this.HouseWhereField = value;
                    this.RaisePropertyChanged("HouseWhere");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportType {
            get {
                return this.ReportTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportTypeField, value) != true)) {
                    this.ReportTypeField = value;
                    this.RaisePropertyChanged("ReportType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToHouseCode {
            get {
                return this.ToHouseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ToHouseCodeField, value) != true)) {
                    this.ToHouseCodeField = value;
                    this.RaisePropertyChanged("ToHouseCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CODDELIVERY", Namespace="http://schemas.datacontract.org/2004/07/Vancl.Finance.Model.Cash")]
    [System.SerializableAttribute()]
    public partial class CODDELIVERY : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> _areatypeField;
        
        private string _boxmodelField;
        
        private System.Nullable<System.DateTime> _datenoField;
        
        private string _expressField;
        
        private System.Nullable<int> _expressidField;
        
        private string _fulladdressField;
        
        private System.Nullable<System.DateTime> _historydateField;
        
        private System.Nullable<int> _historyidField;
        
        private System.Nullable<int> _ismainbranthField;
        
        private int _key_idField;
        
        private string _ordernoField;
        
        private System.Nullable<decimal> _ordertotalpriceField;
        
        private System.Nullable<decimal> _orderweightField;
        
        private System.Nullable<decimal> _receivableField;
        
        private System.Nullable<decimal> _receivedField;
        
        private string _storageField;
        
        private string _warehousenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _areatype {
            get {
                return this._areatypeField;
            }
            set {
                if ((this._areatypeField.Equals(value) != true)) {
                    this._areatypeField = value;
                    this.RaisePropertyChanged("_areatype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _boxmodel {
            get {
                return this._boxmodelField;
            }
            set {
                if ((object.ReferenceEquals(this._boxmodelField, value) != true)) {
                    this._boxmodelField = value;
                    this.RaisePropertyChanged("_boxmodel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _dateno {
            get {
                return this._datenoField;
            }
            set {
                if ((this._datenoField.Equals(value) != true)) {
                    this._datenoField = value;
                    this.RaisePropertyChanged("_dateno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _express {
            get {
                return this._expressField;
            }
            set {
                if ((object.ReferenceEquals(this._expressField, value) != true)) {
                    this._expressField = value;
                    this.RaisePropertyChanged("_express");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _expressid {
            get {
                return this._expressidField;
            }
            set {
                if ((this._expressidField.Equals(value) != true)) {
                    this._expressidField = value;
                    this.RaisePropertyChanged("_expressid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _fulladdress {
            get {
                return this._fulladdressField;
            }
            set {
                if ((object.ReferenceEquals(this._fulladdressField, value) != true)) {
                    this._fulladdressField = value;
                    this.RaisePropertyChanged("_fulladdress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _historydate {
            get {
                return this._historydateField;
            }
            set {
                if ((this._historydateField.Equals(value) != true)) {
                    this._historydateField = value;
                    this.RaisePropertyChanged("_historydate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _historyid {
            get {
                return this._historyidField;
            }
            set {
                if ((this._historyidField.Equals(value) != true)) {
                    this._historyidField = value;
                    this.RaisePropertyChanged("_historyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _ismainbranth {
            get {
                return this._ismainbranthField;
            }
            set {
                if ((this._ismainbranthField.Equals(value) != true)) {
                    this._ismainbranthField = value;
                    this.RaisePropertyChanged("_ismainbranth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _key_id {
            get {
                return this._key_idField;
            }
            set {
                if ((this._key_idField.Equals(value) != true)) {
                    this._key_idField = value;
                    this.RaisePropertyChanged("_key_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _orderno {
            get {
                return this._ordernoField;
            }
            set {
                if ((object.ReferenceEquals(this._ordernoField, value) != true)) {
                    this._ordernoField = value;
                    this.RaisePropertyChanged("_orderno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _ordertotalprice {
            get {
                return this._ordertotalpriceField;
            }
            set {
                if ((this._ordertotalpriceField.Equals(value) != true)) {
                    this._ordertotalpriceField = value;
                    this.RaisePropertyChanged("_ordertotalprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _orderweight {
            get {
                return this._orderweightField;
            }
            set {
                if ((this._orderweightField.Equals(value) != true)) {
                    this._orderweightField = value;
                    this.RaisePropertyChanged("_orderweight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _receivable {
            get {
                return this._receivableField;
            }
            set {
                if ((this._receivableField.Equals(value) != true)) {
                    this._receivableField = value;
                    this.RaisePropertyChanged("_receivable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _received {
            get {
                return this._receivedField;
            }
            set {
                if ((this._receivedField.Equals(value) != true)) {
                    this._receivedField = value;
                    this.RaisePropertyChanged("_received");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _storage {
            get {
                return this._storageField;
            }
            set {
                if ((object.ReferenceEquals(this._storageField, value) != true)) {
                    this._storageField = value;
                    this.RaisePropertyChanged("_storage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _warehousename {
            get {
                return this._warehousenameField;
            }
            set {
                if ((object.ReferenceEquals(this._warehousenameField, value) != true)) {
                    this._warehousenameField = value;
                    this.RaisePropertyChanged("_warehousename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CODDaily", Namespace="http://schemas.datacontract.org/2004/07/Vancl.Finance.Model.Cash")]
    [System.SerializableAttribute()]
    public partial class CODDaily : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> _deliverydateField;
        
        private string _expressField;
        
        private System.Nullable<int> _expressidField;
        
        private int _key_idField;
        
        private System.Nullable<int> _orderQuantityField;
        
        private System.Nullable<decimal> _ordertotalpriceField;
        
        private System.Nullable<decimal> _orderweightField;
        
        private System.Nullable<decimal> _receivableField;
        
        private System.Nullable<int> _receivableOrderQuantityField;
        
        private System.Nullable<decimal> _receivedField;
        
        private string _storageField;
        
        private string _warehousenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _deliverydate {
            get {
                return this._deliverydateField;
            }
            set {
                if ((this._deliverydateField.Equals(value) != true)) {
                    this._deliverydateField = value;
                    this.RaisePropertyChanged("_deliverydate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _express {
            get {
                return this._expressField;
            }
            set {
                if ((object.ReferenceEquals(this._expressField, value) != true)) {
                    this._expressField = value;
                    this.RaisePropertyChanged("_express");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _expressid {
            get {
                return this._expressidField;
            }
            set {
                if ((this._expressidField.Equals(value) != true)) {
                    this._expressidField = value;
                    this.RaisePropertyChanged("_expressid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _key_id {
            get {
                return this._key_idField;
            }
            set {
                if ((this._key_idField.Equals(value) != true)) {
                    this._key_idField = value;
                    this.RaisePropertyChanged("_key_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _orderQuantity {
            get {
                return this._orderQuantityField;
            }
            set {
                if ((this._orderQuantityField.Equals(value) != true)) {
                    this._orderQuantityField = value;
                    this.RaisePropertyChanged("_orderQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _ordertotalprice {
            get {
                return this._ordertotalpriceField;
            }
            set {
                if ((this._ordertotalpriceField.Equals(value) != true)) {
                    this._ordertotalpriceField = value;
                    this.RaisePropertyChanged("_ordertotalprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _orderweight {
            get {
                return this._orderweightField;
            }
            set {
                if ((this._orderweightField.Equals(value) != true)) {
                    this._orderweightField = value;
                    this.RaisePropertyChanged("_orderweight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _receivable {
            get {
                return this._receivableField;
            }
            set {
                if ((this._receivableField.Equals(value) != true)) {
                    this._receivableField = value;
                    this.RaisePropertyChanged("_receivable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _receivableOrderQuantity {
            get {
                return this._receivableOrderQuantityField;
            }
            set {
                if ((this._receivableOrderQuantityField.Equals(value) != true)) {
                    this._receivableOrderQuantityField = value;
                    this.RaisePropertyChanged("_receivableOrderQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _received {
            get {
                return this._receivedField;
            }
            set {
                if ((this._receivedField.Equals(value) != true)) {
                    this._receivedField = value;
                    this.RaisePropertyChanged("_received");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _storage {
            get {
                return this._storageField;
            }
            set {
                if ((object.ReferenceEquals(this._storageField, value) != true)) {
                    this._storageField = value;
                    this.RaisePropertyChanged("_storage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _warehousename {
            get {
                return this._warehousenameField;
            }
            set {
                if ((object.ReferenceEquals(this._warehousenameField, value) != true)) {
                    this._warehousenameField = value;
                    this.RaisePropertyChanged("_warehousename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CODRETURNS", Namespace="http://schemas.datacontract.org/2004/07/Vancl.Finance.Model.Cash")]
    [System.SerializableAttribute()]
    public partial class CODRETURNS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> _areatypeField;
        
        private string _boxmodelField;
        
        private string _consigneeaddressField;
        
        private System.Nullable<System.DateTime> _datenoField;
        
        private System.Nullable<System.DateTime> _deliverydateField;
        
        private string _expressField;
        
        private System.Nullable<int> _expressidField;
        
        private System.Nullable<System.DateTime> _historydateField;
        
        private System.Nullable<int> _historyidField;
        
        private System.Nullable<System.DateTime> _instoragedateField;
        
        private System.Nullable<int> _ismainbranchField;
        
        private System.Nullable<int> _isreceivableorderField;
        
        private System.Nullable<int> _isreturnedField;
        
        private int _key_idField;
        
        private string _ordernoField;
        
        private System.Nullable<decimal> _ordertotalpriceField;
        
        private System.Nullable<decimal> _orderweightField;
        
        private System.Nullable<decimal> _receivableField;
        
        private System.Nullable<decimal> _receivedField;
        
        private string _returnscodeField;
        
        private string _sourcefromField;
        
        private string _storageField;
        
        private string _tohousecodeField;
        
        private System.Nullable<System.DateTime> _tohousedateField;
        
        private string _tohousenameField;
        
        private string _warehousenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _areatype {
            get {
                return this._areatypeField;
            }
            set {
                if ((this._areatypeField.Equals(value) != true)) {
                    this._areatypeField = value;
                    this.RaisePropertyChanged("_areatype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _boxmodel {
            get {
                return this._boxmodelField;
            }
            set {
                if ((object.ReferenceEquals(this._boxmodelField, value) != true)) {
                    this._boxmodelField = value;
                    this.RaisePropertyChanged("_boxmodel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _consigneeaddress {
            get {
                return this._consigneeaddressField;
            }
            set {
                if ((object.ReferenceEquals(this._consigneeaddressField, value) != true)) {
                    this._consigneeaddressField = value;
                    this.RaisePropertyChanged("_consigneeaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _dateno {
            get {
                return this._datenoField;
            }
            set {
                if ((this._datenoField.Equals(value) != true)) {
                    this._datenoField = value;
                    this.RaisePropertyChanged("_dateno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _deliverydate {
            get {
                return this._deliverydateField;
            }
            set {
                if ((this._deliverydateField.Equals(value) != true)) {
                    this._deliverydateField = value;
                    this.RaisePropertyChanged("_deliverydate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _express {
            get {
                return this._expressField;
            }
            set {
                if ((object.ReferenceEquals(this._expressField, value) != true)) {
                    this._expressField = value;
                    this.RaisePropertyChanged("_express");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _expressid {
            get {
                return this._expressidField;
            }
            set {
                if ((this._expressidField.Equals(value) != true)) {
                    this._expressidField = value;
                    this.RaisePropertyChanged("_expressid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _historydate {
            get {
                return this._historydateField;
            }
            set {
                if ((this._historydateField.Equals(value) != true)) {
                    this._historydateField = value;
                    this.RaisePropertyChanged("_historydate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _historyid {
            get {
                return this._historyidField;
            }
            set {
                if ((this._historyidField.Equals(value) != true)) {
                    this._historyidField = value;
                    this.RaisePropertyChanged("_historyid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _instoragedate {
            get {
                return this._instoragedateField;
            }
            set {
                if ((this._instoragedateField.Equals(value) != true)) {
                    this._instoragedateField = value;
                    this.RaisePropertyChanged("_instoragedate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _ismainbranch {
            get {
                return this._ismainbranchField;
            }
            set {
                if ((this._ismainbranchField.Equals(value) != true)) {
                    this._ismainbranchField = value;
                    this.RaisePropertyChanged("_ismainbranch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _isreceivableorder {
            get {
                return this._isreceivableorderField;
            }
            set {
                if ((this._isreceivableorderField.Equals(value) != true)) {
                    this._isreceivableorderField = value;
                    this.RaisePropertyChanged("_isreceivableorder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _isreturned {
            get {
                return this._isreturnedField;
            }
            set {
                if ((this._isreturnedField.Equals(value) != true)) {
                    this._isreturnedField = value;
                    this.RaisePropertyChanged("_isreturned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _key_id {
            get {
                return this._key_idField;
            }
            set {
                if ((this._key_idField.Equals(value) != true)) {
                    this._key_idField = value;
                    this.RaisePropertyChanged("_key_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _orderno {
            get {
                return this._ordernoField;
            }
            set {
                if ((object.ReferenceEquals(this._ordernoField, value) != true)) {
                    this._ordernoField = value;
                    this.RaisePropertyChanged("_orderno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _ordertotalprice {
            get {
                return this._ordertotalpriceField;
            }
            set {
                if ((this._ordertotalpriceField.Equals(value) != true)) {
                    this._ordertotalpriceField = value;
                    this.RaisePropertyChanged("_ordertotalprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _orderweight {
            get {
                return this._orderweightField;
            }
            set {
                if ((this._orderweightField.Equals(value) != true)) {
                    this._orderweightField = value;
                    this.RaisePropertyChanged("_orderweight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _receivable {
            get {
                return this._receivableField;
            }
            set {
                if ((this._receivableField.Equals(value) != true)) {
                    this._receivableField = value;
                    this.RaisePropertyChanged("_receivable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _received {
            get {
                return this._receivedField;
            }
            set {
                if ((this._receivedField.Equals(value) != true)) {
                    this._receivedField = value;
                    this.RaisePropertyChanged("_received");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _returnscode {
            get {
                return this._returnscodeField;
            }
            set {
                if ((object.ReferenceEquals(this._returnscodeField, value) != true)) {
                    this._returnscodeField = value;
                    this.RaisePropertyChanged("_returnscode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _sourcefrom {
            get {
                return this._sourcefromField;
            }
            set {
                if ((object.ReferenceEquals(this._sourcefromField, value) != true)) {
                    this._sourcefromField = value;
                    this.RaisePropertyChanged("_sourcefrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _storage {
            get {
                return this._storageField;
            }
            set {
                if ((object.ReferenceEquals(this._storageField, value) != true)) {
                    this._storageField = value;
                    this.RaisePropertyChanged("_storage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tohousecode {
            get {
                return this._tohousecodeField;
            }
            set {
                if ((object.ReferenceEquals(this._tohousecodeField, value) != true)) {
                    this._tohousecodeField = value;
                    this.RaisePropertyChanged("_tohousecode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _tohousedate {
            get {
                return this._tohousedateField;
            }
            set {
                if ((this._tohousedateField.Equals(value) != true)) {
                    this._tohousedateField = value;
                    this.RaisePropertyChanged("_tohousedate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tohousename {
            get {
                return this._tohousenameField;
            }
            set {
                if ((object.ReferenceEquals(this._tohousenameField, value) != true)) {
                    this._tohousenameField = value;
                    this.RaisePropertyChanged("_tohousename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _warehousename {
            get {
                return this._warehousenameField;
            }
            set {
                if ((object.ReferenceEquals(this._warehousenameField, value) != true)) {
                    this._warehousenameField = value;
                    this.RaisePropertyChanged("_warehousename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CODVISIT", Namespace="http://schemas.datacontract.org/2004/07/Vancl.Finance.Model.Cash")]
    [System.SerializableAttribute()]
    public partial class CODVISIT : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> _areatypeField;
        
        private string _consigneeaddressField;
        
        private System.Nullable<System.DateTime> _datenoField;
        
        private System.Nullable<System.DateTime> _deliverydateField;
        
        private string _expressField;
        
        private System.Nullable<int> _expressidField;
        
        private System.Nullable<System.DateTime> _instoragedateField;
        
        private System.Nullable<int> _ismainbranchField;
        
        private System.Nullable<int> _isreturnedField;
        
        private int _key_idField;
        
        private string _ordernoField;
        
        private System.Nullable<int> _orderquantityField;
        
        private System.Nullable<decimal> _ordertotalpriceField;
        
        private System.Nullable<System.DateTime> _payabledateField;
        
        private System.Nullable<int> _payableidField;
        
        private System.Nullable<decimal> _refundedField;
        
        private System.Nullable<decimal> _shouldrefundField;
        
        private string _storageField;
        
        private string _tohousecodeField;
        
        private System.Nullable<System.DateTime> _tohousedateField;
        
        private string _tohousenameField;
        
        private string _visittypeField;
        
        private string _warehousenameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _areatype {
            get {
                return this._areatypeField;
            }
            set {
                if ((this._areatypeField.Equals(value) != true)) {
                    this._areatypeField = value;
                    this.RaisePropertyChanged("_areatype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _consigneeaddress {
            get {
                return this._consigneeaddressField;
            }
            set {
                if ((object.ReferenceEquals(this._consigneeaddressField, value) != true)) {
                    this._consigneeaddressField = value;
                    this.RaisePropertyChanged("_consigneeaddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _dateno {
            get {
                return this._datenoField;
            }
            set {
                if ((this._datenoField.Equals(value) != true)) {
                    this._datenoField = value;
                    this.RaisePropertyChanged("_dateno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _deliverydate {
            get {
                return this._deliverydateField;
            }
            set {
                if ((this._deliverydateField.Equals(value) != true)) {
                    this._deliverydateField = value;
                    this.RaisePropertyChanged("_deliverydate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _express {
            get {
                return this._expressField;
            }
            set {
                if ((object.ReferenceEquals(this._expressField, value) != true)) {
                    this._expressField = value;
                    this.RaisePropertyChanged("_express");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _expressid {
            get {
                return this._expressidField;
            }
            set {
                if ((this._expressidField.Equals(value) != true)) {
                    this._expressidField = value;
                    this.RaisePropertyChanged("_expressid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _instoragedate {
            get {
                return this._instoragedateField;
            }
            set {
                if ((this._instoragedateField.Equals(value) != true)) {
                    this._instoragedateField = value;
                    this.RaisePropertyChanged("_instoragedate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _ismainbranch {
            get {
                return this._ismainbranchField;
            }
            set {
                if ((this._ismainbranchField.Equals(value) != true)) {
                    this._ismainbranchField = value;
                    this.RaisePropertyChanged("_ismainbranch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _isreturned {
            get {
                return this._isreturnedField;
            }
            set {
                if ((this._isreturnedField.Equals(value) != true)) {
                    this._isreturnedField = value;
                    this.RaisePropertyChanged("_isreturned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int _key_id {
            get {
                return this._key_idField;
            }
            set {
                if ((this._key_idField.Equals(value) != true)) {
                    this._key_idField = value;
                    this.RaisePropertyChanged("_key_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _orderno {
            get {
                return this._ordernoField;
            }
            set {
                if ((object.ReferenceEquals(this._ordernoField, value) != true)) {
                    this._ordernoField = value;
                    this.RaisePropertyChanged("_orderno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _orderquantity {
            get {
                return this._orderquantityField;
            }
            set {
                if ((this._orderquantityField.Equals(value) != true)) {
                    this._orderquantityField = value;
                    this.RaisePropertyChanged("_orderquantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _ordertotalprice {
            get {
                return this._ordertotalpriceField;
            }
            set {
                if ((this._ordertotalpriceField.Equals(value) != true)) {
                    this._ordertotalpriceField = value;
                    this.RaisePropertyChanged("_ordertotalprice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _payabledate {
            get {
                return this._payabledateField;
            }
            set {
                if ((this._payabledateField.Equals(value) != true)) {
                    this._payabledateField = value;
                    this.RaisePropertyChanged("_payabledate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> _payableid {
            get {
                return this._payableidField;
            }
            set {
                if ((this._payableidField.Equals(value) != true)) {
                    this._payableidField = value;
                    this.RaisePropertyChanged("_payableid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _refunded {
            get {
                return this._refundedField;
            }
            set {
                if ((this._refundedField.Equals(value) != true)) {
                    this._refundedField = value;
                    this.RaisePropertyChanged("_refunded");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> _shouldrefund {
            get {
                return this._shouldrefundField;
            }
            set {
                if ((this._shouldrefundField.Equals(value) != true)) {
                    this._shouldrefundField = value;
                    this.RaisePropertyChanged("_shouldrefund");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _storage {
            get {
                return this._storageField;
            }
            set {
                if ((object.ReferenceEquals(this._storageField, value) != true)) {
                    this._storageField = value;
                    this.RaisePropertyChanged("_storage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tohousecode {
            get {
                return this._tohousecodeField;
            }
            set {
                if ((object.ReferenceEquals(this._tohousecodeField, value) != true)) {
                    this._tohousecodeField = value;
                    this.RaisePropertyChanged("_tohousecode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> _tohousedate {
            get {
                return this._tohousedateField;
            }
            set {
                if ((this._tohousedateField.Equals(value) != true)) {
                    this._tohousedateField = value;
                    this.RaisePropertyChanged("_tohousedate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _tohousename {
            get {
                return this._tohousenameField;
            }
            set {
                if ((object.ReferenceEquals(this._tohousenameField, value) != true)) {
                    this._tohousenameField = value;
                    this.RaisePropertyChanged("_tohousename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _visittype {
            get {
                return this._visittypeField;
            }
            set {
                if ((object.ReferenceEquals(this._visittypeField, value) != true)) {
                    this._visittypeField = value;
                    this.RaisePropertyChanged("_visittype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _warehousename {
            get {
                return this._warehousenameField;
            }
            set {
                if ((object.ReferenceEquals(this._warehousenameField, value) != true)) {
                    this._warehousenameField = value;
                    this.RaisePropertyChanged("_warehousename");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceClient.ICOD")]
    public interface ICOD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOD/GetCODDelivery", ReplyAction="http://tempuri.org/ICOD/GetCODDeliveryResponse")]
        CODDELIVERY[] GetCODDelivery(CODParameter codPar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOD/GetCODDeliveryDaily", ReplyAction="http://tempuri.org/ICOD/GetCODDeliveryDailyResponse")]
        CODDaily[] GetCODDeliveryDaily(CODParameter codPar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOD/GetCODReturns", ReplyAction="http://tempuri.org/ICOD/GetCODReturnsResponse")]
        CODRETURNS[] GetCODReturns(CODParameter codPara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOD/GetCODReturnsDaily", ReplyAction="http://tempuri.org/ICOD/GetCODReturnsDailyResponse")]
        CODDaily[] GetCODReturnsDaily(CODParameter codPara);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOD/GetCODVisit", ReplyAction="http://tempuri.org/ICOD/GetCODVisitResponse")]
        CODVISIT[] GetCODVisit(CODParameter codPar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICOD/GetCODVisitDaily", ReplyAction="http://tempuri.org/ICOD/GetCODVisitDailyResponse")]
        CODVISIT[] GetCODVisitDaily(CODParameter codPar);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICODChannel : ICOD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CODClient : System.ServiceModel.ClientBase<ICOD>, ICOD {
        
        public CODClient() {
        }
        
        public CODClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CODClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CODClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CODClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CODDELIVERY[] GetCODDelivery(CODParameter codPar) {
            return base.Channel.GetCODDelivery(codPar);
        }
        
        public CODDaily[] GetCODDeliveryDaily(CODParameter codPar) {
            return base.Channel.GetCODDeliveryDaily(codPar);
        }
        
        public CODRETURNS[] GetCODReturns(CODParameter codPara) {
            return base.Channel.GetCODReturns(codPara);
        }
        
        public CODDaily[] GetCODReturnsDaily(CODParameter codPara) {
            return base.Channel.GetCODReturnsDaily(codPara);
        }
        
        public CODVISIT[] GetCODVisit(CODParameter codPar) {
            return base.Channel.GetCODVisit(codPar);
        }
        
        public CODVISIT[] GetCODVisitDaily(CODParameter codPar) {
            return base.Channel.GetCODVisitDaily(codPar);
        }
    }
}
