//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4961
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFD.FMS.WEB.WcfSsoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://schemas.datacontract.org/2004/07/RFD.SSO.Server.Domain")]
    [System.SerializableAttribute()]
    public partial class LoginRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebSiteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdField, value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebSite {
            get {
                return this.WebSiteField;
            }
            set {
                if ((object.ReferenceEquals(this.WebSiteField, value) != true)) {
                    this.WebSiteField = value;
                    this.RaisePropertyChanged("WebSite");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfSsoService.ISSOService")]
    public interface ISSOService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSOService/Login", ReplyAction="http://tempuri.org/ISSOService/LoginResponse")]
        bool Login(out string token, RFD.FMS.WEB.WcfSsoService.LoginRequest loginRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSOService/Logout", ReplyAction="http://tempuri.org/ISSOService/LogoutResponse")]
        void Logout(string siteId, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSOService/ValidateToken", ReplyAction="http://tempuri.org/ISSOService/ValidateTokenResponse")]
        bool ValidateToken(out System.Data.DataSet userData, string siteId, string ip, string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSOService/GetLoginUrl", ReplyAction="http://tempuri.org/ISSOService/GetLoginUrlResponse")]
        string GetLoginUrl();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISSOService/GetWebAuthHandler", ReplyAction="http://tempuri.org/ISSOService/GetWebAuthHandlerResponse")]
        string GetWebAuthHandler(string siteId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ISSOServiceChannel : RFD.FMS.WEB.WcfSsoService.ISSOService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class SSOServiceClient : System.ServiceModel.ClientBase<RFD.FMS.WEB.WcfSsoService.ISSOService>, RFD.FMS.WEB.WcfSsoService.ISSOService {
        
        public SSOServiceClient() {
        }
        
        public SSOServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SSOServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSOServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SSOServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(out string token, RFD.FMS.WEB.WcfSsoService.LoginRequest loginRequest) {
            return base.Channel.Login(out token, loginRequest);
        }
        
        public void Logout(string siteId, string token) {
            base.Channel.Logout(siteId, token);
        }
        
        public bool ValidateToken(out System.Data.DataSet userData, string siteId, string ip, string token) {
            return base.Channel.ValidateToken(out userData, siteId, ip, token);
        }
        
        public string GetLoginUrl() {
            return base.Channel.GetLoginUrl();
        }
        
        public string GetWebAuthHandler(string siteId) {
            return base.Channel.GetWebAuthHandler(siteId);
        }
    }
}
