//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.239
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RFD.FMS.WEB.RequisitionedService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanInfoDto", Namespace="http://schemas.datacontract.org/2004/07/Vancl.SCMS.CommonModel.Stock")]
    [System.SerializableAttribute()]
    public partial class LoanInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddresseeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddresseePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorrowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CashierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FormTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PassTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SourceTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addressee {
            get {
                return this.AddresseeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddresseeField, value) != true)) {
                    this.AddresseeField = value;
                    this.RaisePropertyChanged("Addressee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddresseePhone {
            get {
                return this.AddresseePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.AddresseePhoneField, value) != true)) {
                    this.AddresseePhoneField = value;
                    this.RaisePropertyChanged("AddresseePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Borrower {
            get {
                return this.BorrowerField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowerField, value) != true)) {
                    this.BorrowerField = value;
                    this.RaisePropertyChanged("Borrower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cashier {
            get {
                return this.CashierField;
            }
            set {
                if ((object.ReferenceEquals(this.CashierField, value) != true)) {
                    this.CashierField = value;
                    this.RaisePropertyChanged("Cashier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptName {
            get {
                return this.DeptNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNameField, value) != true)) {
                    this.DeptNameField = value;
                    this.RaisePropertyChanged("DeptName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptNo {
            get {
                return this.DeptNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNoField, value) != true)) {
                    this.DeptNoField = value;
                    this.RaisePropertyChanged("DeptNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormCode {
            get {
                return this.FormCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FormCodeField, value) != true)) {
                    this.FormCodeField = value;
                    this.RaisePropertyChanged("FormCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> FormType {
            get {
                return this.FormTypeField;
            }
            set {
                if ((this.FormTypeField.Equals(value) != true)) {
                    this.FormTypeField = value;
                    this.RaisePropertyChanged("FormType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maker {
            get {
                return this.MakerField;
            }
            set {
                if ((object.ReferenceEquals(this.MakerField, value) != true)) {
                    this.MakerField = value;
                    this.RaisePropertyChanged("Maker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdField, value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PassTime {
            get {
                return this.PassTimeField;
            }
            set {
                if ((this.PassTimeField.Equals(value) != true)) {
                    this.PassTimeField = value;
                    this.RaisePropertyChanged("PassTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductTypeId {
            get {
                return this.ProductTypeIdField;
            }
            set {
                if ((this.ProductTypeIdField.Equals(value) != true)) {
                    this.ProductTypeIdField = value;
                    this.RaisePropertyChanged("ProductTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurposeName {
            get {
                return this.PurposeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeNameField, value) != true)) {
                    this.PurposeNameField = value;
                    this.RaisePropertyChanged("PurposeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurposeNo {
            get {
                return this.PurposeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeNoField, value) != true)) {
                    this.PurposeNoField = value;
                    this.RaisePropertyChanged("PurposeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SourceType {
            get {
                return this.SourceTypeField;
            }
            set {
                if ((this.SourceTypeField.Equals(value) != true)) {
                    this.SourceTypeField = value;
                    this.RaisePropertyChanged("SourceType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoanModelDto", Namespace="http://schemas.datacontract.org/2004/07/Vancl.SCMS.CommonModel.Stock")]
    [System.SerializableAttribute()]
    public partial class LoanModelDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RFD.FMS.WEB.RequisitionedService.AddressType AddrTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorrowerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeptNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RFD.FMS.WEB.RequisitionedService.ForeignAddressInfo ForeignAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RFD.FMS.WEB.RequisitionedService.HomeAddressInfo HomeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<RFD.FMS.WEB.RequisitionedService.ProductView> ProductListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiveTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransferWayField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RFD.FMS.WEB.RequisitionedService.AddressType AddrType {
            get {
                return this.AddrTypeField;
            }
            set {
                if ((this.AddrTypeField.Equals(value) != true)) {
                    this.AddrTypeField = value;
                    this.RaisePropertyChanged("AddrType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Borrower {
            get {
                return this.BorrowerField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowerField, value) != true)) {
                    this.BorrowerField = value;
                    this.RaisePropertyChanged("Borrower");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeptNo {
            get {
                return this.DeptNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DeptNoField, value) != true)) {
                    this.DeptNoField = value;
                    this.RaisePropertyChanged("DeptNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RFD.FMS.WEB.RequisitionedService.ForeignAddressInfo ForeignAddress {
            get {
                return this.ForeignAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ForeignAddressField, value) != true)) {
                    this.ForeignAddressField = value;
                    this.RaisePropertyChanged("ForeignAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RFD.FMS.WEB.RequisitionedService.HomeAddressInfo HomeAddress {
            get {
                return this.HomeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeAddressField, value) != true)) {
                    this.HomeAddressField = value;
                    this.RaisePropertyChanged("HomeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Maker {
            get {
                return this.MakerField;
            }
            set {
                if ((object.ReferenceEquals(this.MakerField, value) != true)) {
                    this.MakerField = value;
                    this.RaisePropertyChanged("Maker");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<RFD.FMS.WEB.RequisitionedService.ProductView> ProductList {
            get {
                return this.ProductListField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductListField, value) != true)) {
                    this.ProductListField = value;
                    this.RaisePropertyChanged("ProductList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurposeNo {
            get {
                return this.PurposeNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeNoField, value) != true)) {
                    this.PurposeNoField = value;
                    this.RaisePropertyChanged("PurposeNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiveTime {
            get {
                return this.ReceiveTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiveTimeField, value) != true)) {
                    this.ReceiveTimeField = value;
                    this.RaisePropertyChanged("ReceiveTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferID {
            get {
                return this.TransferIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferIDField, value) != true)) {
                    this.TransferIDField = value;
                    this.RaisePropertyChanged("TransferID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransferWay {
            get {
                return this.TransferWayField;
            }
            set {
                if ((object.ReferenceEquals(this.TransferWayField, value) != true)) {
                    this.TransferWayField = value;
                    this.RaisePropertyChanged("TransferWay");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForeignAddressInfo", Namespace="http://schemas.datacontract.org/2004/07/Vancl.SCMS.CommonModel.Stock")]
    [System.SerializableAttribute()]
    public partial class ForeignAddressInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Street2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName {
            get {
                return this.CountryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryNameField, value) != true)) {
                    this.CountryNameField = value;
                    this.RaisePropertyChanged("CountryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postalcode {
            get {
                return this.PostalcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalcodeField, value) != true)) {
                    this.PostalcodeField = value;
                    this.RaisePropertyChanged("Postalcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street1 {
            get {
                return this.Street1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street1Field, value) != true)) {
                    this.Street1Field = value;
                    this.RaisePropertyChanged("Street1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street2 {
            get {
                return this.Street2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Street2Field, value) != true)) {
                    this.Street2Field = value;
                    this.RaisePropertyChanged("Street2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HomeAddressInfo", Namespace="http://schemas.datacontract.org/2004/07/Vancl.SCMS.CommonModel.Stock")]
    [System.SerializableAttribute()]
    public partial class HomeAddressInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddresseeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobilePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostalcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Addressee {
            get {
                return this.AddresseeField;
            }
            set {
                if ((object.ReferenceEquals(this.AddresseeField, value) != true)) {
                    this.AddresseeField = value;
                    this.RaisePropertyChanged("Addressee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNo {
            get {
                return this.CardNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNoField, value) != true)) {
                    this.CardNoField = value;
                    this.RaisePropertyChanged("CardNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobilePhone {
            get {
                return this.MobilePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobilePhoneField, value) != true)) {
                    this.MobilePhoneField = value;
                    this.RaisePropertyChanged("MobilePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Postalcode {
            get {
                return this.PostalcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostalcodeField, value) != true)) {
                    this.PostalcodeField = value;
                    this.RaisePropertyChanged("Postalcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Province {
            get {
                return this.ProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinceField, value) != true)) {
                    this.ProvinceField = value;
                    this.RaisePropertyChanged("Province");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressType", Namespace="http://schemas.datacontract.org/2004/07/Vancl.SCMS.CommonModel.Stock")]
    public enum AddressType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HomeAddr = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForeignAddr = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductView", Namespace="http://schemas.datacontract.org/2004/07/Vancl.SCMS.CommonModel.Stock")]
    [System.SerializableAttribute()]
    public partial class ProductView : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SKUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SellPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SKU {
            get {
                return this.SKUField;
            }
            set {
                if ((object.ReferenceEquals(this.SKUField, value) != true)) {
                    this.SKUField = value;
                    this.RaisePropertyChanged("SKU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SellPrice {
            get {
                return this.SellPriceField;
            }
            set {
                if ((this.SellPriceField.Equals(value) != true)) {
                    this.SellPriceField = value;
                    this.RaisePropertyChanged("SellPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DealResult", Namespace="http://schemas.datacontract.org/2004/07/Vancl.SCMS.CommonModel")]
    [System.SerializableAttribute()]
    public partial class DealResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Vancl.SCMS.Services", ConfigurationName="RequisitionedService.ILoanService")]
    public interface ILoanService {
        
        [System.ServiceModel.OperationContractAttribute(Action="Vancl.SCMS.Services/ILoanService/GetLoanInfoByOrderId", ReplyAction="Vancl.SCMS.Services/ILoanService/GetLoanInfoByOrderIdResponse")]
        System.Collections.Generic.List<RFD.FMS.WEB.RequisitionedService.LoanInfoDto> GetLoanInfoByOrderId(System.Collections.Generic.List<string> orderIds);
        
        [System.ServiceModel.OperationContractAttribute(Action="Vancl.SCMS.Services/ILoanService/CreateLoan", ReplyAction="Vancl.SCMS.Services/ILoanService/CreateLoanResponse")]
        RFD.FMS.WEB.RequisitionedService.DealResult CreateLoan(RFD.FMS.WEB.RequisitionedService.LoanModelDto model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILoanServiceChannel : RFD.FMS.WEB.RequisitionedService.ILoanService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoanServiceClient : System.ServiceModel.ClientBase<RFD.FMS.WEB.RequisitionedService.ILoanService>, RFD.FMS.WEB.RequisitionedService.ILoanService {
        
        public LoanServiceClient() {
        }
        
        public LoanServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoanServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoanServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<RFD.FMS.WEB.RequisitionedService.LoanInfoDto> GetLoanInfoByOrderId(System.Collections.Generic.List<string> orderIds) {
            return base.Channel.GetLoanInfoByOrderId(orderIds);
        }
        
        public RFD.FMS.WEB.RequisitionedService.DealResult CreateLoan(RFD.FMS.WEB.RequisitionedService.LoanModelDto model) {
            return base.Channel.CreateLoan(model);
        }
    }
}
